# domain = [
#     "WSCNYC.ORG",
#     "AMNH.ORG",
#     "AMSBRONX.ORG",
#     "AOITHS.ORG",
#     "BCS448.ORG",
#     "BRONXSOFTWARE.ORG",
#     "CIX.CSI.CUNY.EDU",
#     "ESCHS.ORG",
#     "EWSIS.ORG",
#     "JOHNDEWEYHIGHSCHOOL.ORG",
#     "KIPPNY.ORG",
#     "MANHATTANBRIDGESHS.ORG",
#     "MYCHAH.ORG",
#     "PS1CONNECTS.ORG",
#     "PS170X.ORG",
#     "PS321.INFO",
#     "PS372.NET",
#     "P94M.ORG",
#     "SCHOOLS.NYC.GOV",
#     "ACADEMYOFTHECITY.ORG",
#     "AMNH.ORG",
#     "AMSBRONX.ORG",
#     "AOITHS.ORG",
#     "AOITHS.ORG",
#     "ARCHIMEDESACADEMY.ORG",
#     "BAYCHESTERWAVES.ORG",
#     "BAYSIDEHIGHSCHOOL.ORG",
#     "BCS448.ORG",
#     "BEACONSCHOOL.ORG",
#     "BNS146.ORG",
#     "BRONXARENA.ORG",
#     "BRONXDALEHS.ORG",
#     "BRONXSOFTWARE.ORG",
#     "BROOKLYNBEES.ORG",
#     "CIX.CSI.CUNY.EDU",
#     "COLUMBIASECONDARY.ORG",
#     "CSSJBRONX.ORG",
#     "DIGITALTECHHS.ORG",
#     "EPICSCHOOLSNYC.ORG",
#     "ESCHS.ORG",
#     "ESSEXSTREETACADEMY.ORG",
#     "EWSIS.ORG",
#     "FANNIELOU.ORG",
#     "FDA2.NET",
#     "FLHFHS.ORG",
#     "FUTURELEADERSINSTITUTE.ORG",
#     "HSARTSTECH.ORG",
#     "HSMSE.ORG",
#     "IHPCH.ORG",
#     "JOHNDEWEYHIGHSCHOOL.ORG",
#     "KIPPNY.ORG",
#     "KIPPNYC.ORG",
#     "K051.ORG",
#     "K497.ORG",
#     "LANGUAGEANDINNOVATION.ORG",
#     "LEADERS6-12.ORG",
#     "MANHATTANBRIDGESHS.ORG",
#     "MCNDHS.COM",
#     "MILLENNIUMBROOKLYNHS.ORG",
#     "MOTTHALL2.ORG",
#     "MYBIHS.ORG",
#     "MYCHAH.ORG",
#     "NEWHEIGHTSMS.ORG",
#     "NYC.GOV",
#     "NYCLABSCHOOL.ORG",
#     "OWMS.ORG",
#     "PPASSHARE.ORG",
#     "PSICOLOGOS.COM",
#     "PSMS108.ORG",
#     "PSMS161.ORG",
#     "PSMS29.COM",
#     "PS1CONNECTS.ORG",
#     "PS10.ORG",
#     "PS107.ORG",
#     "PS116.ORG",
#     "PS130BROOKLYN.COM",
#     "PS151K.ORG",
#     "PS261BROOKLYN.ORG",
#     "PS277X.COM",
#     "PS29BK.ORG",
#     "PS295.ORG",
#     "PS330Q.ORG",
#     "PS361.ORG",
#     "PS372.NET",
#     "PS372.ORG",
#     "PS39.ORG",
#     "PS39.ORG",
#     "PS57.US",
#     "PS58ONLINE.ORG",
#     "PS6NYC.COM",
#     "PS61X.ORG",
#     "PS72M.ORG",
#     "PS72M.ORG",
#     "PS89.ORG",
#     "P94M.ORG",
#     "SCHOLARSNYC.COM",
#     "SCHOOLS.NYC",
#     "SCHOOLS.NYC.GOV",
#     "SCHOOLS.NYC.ORG",
#     "SLJHS.ORG",
#     "TSMSONLINE.ORG",
#     "TYWLSBROOKLYN.ORG",
#     "UAMUSICANDART.ORG",
#     "UPPUBLICSCHOOLS.ORG",
#     "VALIDUSPREP.ORG",
#     "WHEELSNYC.ORG",
#     "WILLIAMSBURGPREP.ORG",
#     "CIX.CSI.CUNY.EDU",
#     "MCNDHS.COM",
#     "MCNDHS.COM",
#     "CRISTOREYBROOKLYN.ORG",
#     "CHARTER.NEWVISIONS.ORG",
#     "CIX.CSI.CUNY.EDU",
#     "ESCHS.ORG",
#     "MS131.ORG",
#     "MYBIHS.ORG",
#     "MYBIHS.ORG",
#     "MYBIHS.ORG",
#     "PS32.ORG",
#     "PS503ONLINE.ORG",
#     "ACADEMYOFTHECITY.ORG",
#     "ACADEMYOFTHECITY.ORG",
#     "AMSBRONX.ORG",
#     "AOITHS.ORG",
#     "SCHOOLS.NY.GOV",
#     "SCHOOLSNYC.GOV",
#     "VALIDUSPREP.ORG",
#     "AMSBRONX.ORG",
#     "AMSBRONX.ORG",
#     "BCS448.ORG",
#     "BCS448.ORG",
#     "BRONXSOFTWARE.ORG",
#     "CSSJBRONX.ORG",
#     "EPICSCHOOLSNYC.ORG",
#     "ESCHS.ORG",
#     "EWSIS.ORG",
#     "FLHFHS.ORG",
#     "HSFI.US",
#     "HSFI.US",
#     "HSMSE.ORG",
#     "HSTAT.ORG",
#     "MILLENNIUMBROOKLYNHS.ORG",
#     "MS233.ORG",
#     "MYBIHS.ORG",
#     "PAIHSMONROE.ORG",
#     "PETRIDESSCHOOL.COM",
#     "SLJHS.ORG",
#     "EWSIS.ORG",
#     "HSFI.US",
#     "ICHSBRONX.ORG",
#     "MYBIHS.ORG"
# ]

domain = [
    '498VANNESTACADEMY.ORG',
    '368STARACADEMY.ORG',
    '2NYCBOE.NET',
    'WSCNYC.ORG',
    'WILLIAMSBURGPREP.ORG',
    'WHEELSNYC.ORG',
    'VNSNY.ORG',
    'VALIDUSPREP.ORG',
    'URBANACADEMY.ORG',
    'UPPUBLICSCHOOLS.ORG',
    'UAMUSICANDART.ORG',
    'TYWLSBROOKLYN.ORG',
    'TSMSONLINE.ORG',
    'TOTTENVILLEHS.COM',
    'SLJHS.ORG',
    'SGL378.ORG',
    'SCHOOLSNYC.GOV',
    'SCHOOLSNYC.DOE.ORG',
    'SCHOOLS.NYC.ORG',
    'SCHOOLS.NYC.GOV.ORG',
    'SCHOOLS.NYC.GOV',
    'SCHOOLS.NYC.EDU',
    'SCHOOLS.NYC.COM',
    'SCHOOLS.NYC',
    'SCHOOLS.NY.GOV',
    'SCHOOLS.NET.GOV',
    'SCHOOLS.GOV.NYC',
    'SCHOOLS.GOV.NET',
    'SCHOOLS.GOV',
    'SCHOOLS.EDU.NYC.GOV',
    'SCHOOLS.EDU',
    'SCHOOLS.COM',
    'SCHOOL.NYC.GOV',
    'SCHOOL.COM',
    'SCHOOIS.NYC.GOV',
    'SCHOLARSNYC.COM',
    'ROCHEA@PS062.ORG',
    'P94M.ORG',
    'P017X.ORG',
    'PTECHNYC.ORG',
    'PS97.ORG',
    'PS9SI.ORG',
    'PS9.ORG',
    'PS89X.COM',
    'PS89.ORG',
    'PS82Q.ORG',
    'PS78.COM',
    'PS72M.ORG',
    'PS66Q.COM',
    'PS61X.ORG',
    'PS6X.ORG',
    'PS6NYC.COM',
    'PS595BRONX.ORG',
    'PS58ONLINE.ORG',
    'PS57.US',
    'PS532NEWBRIDGES.ORG',
    'PS52K.COM',
    'PS503ONLINE.ORG',
    'PS42M.ORG',
    'PS41.ORG',
    'PS39.ORG',
    'PS372.ORG',
    'PS372.NET',
    'PS361.ORG',
    'PS354.ORG',
    'PS347.ORG',
    'PS343.ORG',
    'PS330Q.ORG',
    'PS321.ORG',
    'PS32.ORG',
    'PS3BROOKLYN.ORG',
    'PS295.ORG',
    'PS290.ORG',
    'PS29BK.ORG',
    'PS277X.COM',
    'PS261BROOKLYN.ORG',
    'PS236.ORG',
    'PS234.ORG',
    'PS212Q.COM',
    'PS204.ORG',
    'PS2M.INFO',
    'PS19R.COM',
    'PS184M.ORG',
    'PS183.ORG',
    'PS18R.ORG',
    'PS171.ORG',
    'PS170X.ORG',
    'PS163M.ORG',
    'PS16SCHOOL.ORG',
    'PS158.NET',
    'PS154.ORG',
    'PS151K.ORG',
    'PS150Q.ORG',
    'PS146.ORG',
    'PS145.ORG',
    'PS142M.ORG',
    'PS139.ORG',
    'PS133.ORG',
    'PS130BROOKLYN.COM',
    'PS123K.COM',
    'PS116.ORG',
    'PS111X.COM',
    'PS108Q.COM',
    'PS107X.ORG',
    'PS107.ORG',
    'PS102Q.ORG',
    'PS10.ORG',
    'PS1CONNECTS.ORG',
    'PS062.ORG',
    'PSMS46.ORG',
    'PSMS29.ORG',
    'PSMS29.COM',
    'PSMS280.COM',
    'PSMS206.ORG',
    'PSMS161.ORG',
    'PSMS108.ORG',
    'PSLCONNECT.ORG',
    'PSI3O6ROOKI4N.COM',
    'PSIS226.ORG',
    'PSIS217.NET',
    'PSIS104.COM',
    'PSICOLOGOS.COM',
    'PSBNYC.COM',
    'PPASSHARE.ORG',
    'PETRIDESSCHOOL.COM',
    'PAIHSMONROE.ORG',
    'OWMS.ORG',
    'NYPD.ORG',
    'NYCSCHOOLS.GOV',
    'NYCSCHOOLS.EDU',
    'NYCLABSCHOOL.ORG',
    'NYCE.BOE.NET',
    'NYCDOE.ORG',
    'NYCDOE.NET',
    'NYCDOE.GOV',
    'NYCDOE.EDU',
    'NYCDOE.COM',
    'NYCBOR.NET',
    'NYCBOE.ORG',
    'NYCBOE.NET',
    'NYCBOE.GOV',
    'NYCBOE.EDU',
    'NYCBOE.COM',
    'NYCBOD.NET',
    'NYC.SCHOOLS.ORG',
    'NYC.SCHOOLS.NET',
    'NYC.SCHOOLS.GOV',
    'NYC.GOV',
    'NYC.DOE.GOV',
    'NYC.BOE.NET',
    'NYC.BOE',
    'NNCDOE.GOV',
    'NEWYORKEDGE.ORG',
    'NEWHEIGHTSMS.ORG',
    'MYCHAH.ORG',
    'MYBIHS.ORG',
    'MS363APLE.ORG',
    'MS233.ORG',
    'MS131.ORG',
    'MOTTHALL2.ORG',
    'MILLENNIUMBROOKLYNHS.ORG',
    'MIHS.NYCDOE.ORG',
    'MHVPSCHOOL.COM',
    'MCNDHS.COM',
    'MASTERYCOLLABORATIVE.ORG',
    'LMC896.ORG',
    'LMCMC.COM',
    'LICHS.ORG',
    'LEADERS6-12.ORG',
    'LANGUAGEANDINNOVATION.ORG',
    'K497.ORG',
    'K051.ORG',
    'KIPPNYC.ORG',
    'KIPPNY.ORG',
    'IS89.ORG',
    'IS27UFT.ORG',
    'IHPCH.ORG',
    'ICHSBRONX.ORG',
    'HSTAT.ORG',
    'HSMSE.ORG',
    'HSMPBK.ORG',
    'HSFI.US',
    'HSARTSTECH.ORG',
    'HRA.NYC.GOV',
    'HIGHBRIDGEGREEN.ORG',
    'HEALTH.NYC.GOV',
    'FUTURELEADERSINSTITUTE.ORG',
    'FLHFHS.ORG',
    'FEC384.ORG',
    'FDA2.NET',
    'FANNIELOU.ORG',
    'EWSIS.ORG',
    'ESSEXSTREETACADEMY.ORG',
    'ESCHS.ORG',
    'EPICSCHOOLSNYC.ORG',
    'EASTBRONXACADEMY.ORG',
    'EARWSHS.NET',
    'DOE.ORG',
    'DOE.COM',
    'DIGITALTECHHS.ORG',
    'CYPRESSHILLS.ORG',
    'CSSJBRONX.ORG',
    'CRISTOREYBROOKLYN.ORG',
    'CPE-HS.ORG',
    'COLUMBIASECONDARY.ORG',
    'CIX.CSI.CUNY.EDU',
    'CHARTER.NEWVISIONS.ORG',
    'BXSLF.ORG',
    'BROOKLYNLANDMARK.ORG',
    'BROOKLYNBEES.ORG',
    'BROOKLYNARTSHS.NYC',
    'BROOKLYNARTSELEMENTARY.ORG',
    'BRONXSOFTWARE.ORG',
    'BRONXHAVEN.ORG',
    'BRONXDALEHS.ORG',
    'BRONXARENA.ORG',
    'BOE.NET',
    'BNS146.ORG',
    'BKLYNDAILYDISCOVERY.ORG',
    'BEACONSCHOOL.ORG',
    'BCS448.ORG',
    'BAYSIDEHIGHSCHOOL.ORG',
    'BAYCHESTERWAVES.ORG',
    'ARCHIMEDESACADEMY.ORG',
    'AOITHS.ORG',
    'AMSBRONX.ORG',
    'AMNH.ORG',
    'AELNYC.ORG',
    'ACADEMYOFTHECITY.ORG'
]

import json

# Function to read JSON data from a file
def read_json_file(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data

# Function to check if a specific word exists in the JSON data
def check_word_in_json(data, word):
    if isinstance(data, dict):
        for key, value in data.items():
            if check_word_in_json(key, word) or check_word_in_json(value, word):
                return True
    elif isinstance(data, list):
        for item in data:
            if check_word_in_json(item, word):
                return True
    elif isinstance(data, str):
        if word in data:
            return True
    return False

# Read the JSON data from the file
file_path = 'new_output_file.json'
json_data = read_json_file(file_path)

existed = []
nothere = []
# Check if a specific word exists in the JSON data
for word in domain:
    exists = check_word_in_json(json_data, word.lower())
    if exists:
        existed.append(word.lower())
    else:
        nothere.append(word.lower())

print(existed)
print(f"\nNot in the list: {nothere}")
